### ISSUE TITLE
Requesting to add Premiumize debrid option in Jackettio addon.

### ISSUE THREAD

**Issue by Beingjustinroyfernandes** [arvida42/jackettio#26] opened 2024-10-03 05:56 UTC
Hi @arvida42 

Currently have a Premiumize API key and i am trying to add the Jackettio v1.3.0 addon in my Stremio account. However, I am not seeing an option to integrate Premiumize within the addon. Can you please add an option over there for Premiumize debrid.

**Comment by arvida42** [comment] 2024-10-03 20:46
Duplicate of #9

**Closed by arvida42** 2024-10-03 20:46 UTC
